// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirillinED/shortener/internal/app (interfaces: Application)

// Package mock_foundation is a generated GoMock package.
package foundation

import (
	"github.com/KirillinED/shortener/internal/config"
	services "github.com/KirillinED/shortener/internal/services/shortener"
	reflect "reflect"

	interfaces "github.com/KirillinED/shortener/internal/storage/interfaces"
	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// Bootstrap mocks base method.
func (m *MockApplication) Bootstrap() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Bootstrap")
}

// Bootstrap indicates an expected call of Bootstrap.
func (mr *MockApplicationMockRecorder) Bootstrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bootstrap", reflect.TypeOf((*MockApplication)(nil).Bootstrap))
}

// GetConfig mocks base method.
func (m *MockApplication) GetConfig() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockApplicationMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockApplication)(nil).GetConfig))
}

// GetLogger mocks base method.
func (m *MockApplication) GetLogger() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockApplicationMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockApplication)(nil).GetLogger))
}

// GetShortenerService mocks base method.
func (m *MockApplication) GetShortenerService() *services.ShortenerService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortenerService")
	ret0, _ := ret[0].(*services.ShortenerService)
	return ret0
}

// GetShortenerService indicates an expected call of GetShortenerService.
func (mr *MockApplicationMockRecorder) GetShortenerService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortenerService", reflect.TypeOf((*MockApplication)(nil).GetShortenerService))
}

// GetStorage mocks base method.
func (m *MockApplication) GetStorage() interfaces.Storage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorage")
	ret0, _ := ret[0].(interfaces.Storage)
	return ret0
}

// GetStorage indicates an expected call of GetStorage.
func (mr *MockApplicationMockRecorder) GetStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorage", reflect.TypeOf((*MockApplication)(nil).GetStorage))
}

// Shutdown mocks base method.
func (m *MockApplication) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockApplicationMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockApplication)(nil).Shutdown))
}
